server:
  port: 8080
  servlet:
    context-path: /jfcloud
logging:
  level:
    root: INFO
spring:
  jpa:
    hibernate:
      ddl-auto: update #更新表结构
    show-sql: true  #打印sql
  database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jfcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: fams
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
camels:
  home: E:\workspace\jfcloud\jfcloud
